### ISSUE TITLE
Fetching lyrics ? Can PMRP show lyrics of songs ?

### ISSUE THREAD

**Issue by penguin31** [hakerdefo/pmrp#1]

**Comment by hakerdefo** [comment]
Internet radio streams don't carry data (Artist, Album, Title, Etc.) tags so getting the lyrics in a shell script is next to impossible. It can though be easily implemented for audio players, for example have a look at these,
[cmus-lyrics](https://github.com/hakerdefo/cmus-lyrics)
[moc-lyrics](https://github.com/hakerdefo/moc-lyrics)

Cheers!!!
