### ISSUE TITLE
Radio Paradise

### ISSUE THREAD

**Issue by supertevran** [hakerdefo/pmrp#11]
Hi. Could you pls. be so kind as to add the 4 great Radio Paradise Stream Links:
https://radioparadise.com/listen/stream-links
mp3 or ogg streams will do for many for sure. Thx.

**Comment by hakerdefo** [comment]
Hi there @supertevran 
Thanks for suggesting these stations. :+1: 
I've added them to pmrp. You can find them here,
Medley -> 35 - Radio Paradise World
Medley -> 40 - Radio Paradise Mix
Medley -> 41 - Radio Paradise Mallow
Rock -> 09 - Radio Paradise Rock

Enjoy :smile:

**Comment by supertevran** [comment]
Dear "hakerdefo"
This is really amazing and absolutely great - mindblowing! I make a small remark and just a couple of hours later you not only reply but make a dream come true!
These current times are really crazy, weird. The pandemic is still affecting all of us. It's just great that there are people like you around.
Could you pls. doublecheck. I've tested all of them right now and unfortunately they are not playing (40 & 41) ... just silence ;-) 12 in Medley is OK. 9 in Rock Music is silence as well.

**Comment by hakerdefo** [comment]
@supertevran 
Sorry about the inconvenience there. Please get the updated version of `pmrp` as I've fixed the issue and all of the Radio Paradise stations should work now, hopefully :wink: 
And the pandemic has robbed me of everything that I used to call life and has given me the depression that is never ending. Anyway this ain't the place to discuss my pain and sorrow. Sorry about that.
Have a great day/night head.
